// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cosinor_pvals_cpp
NumericVector cosinor_pvals_cpp(const NumericMatrix& expr, const NumericVector& times, double period);
RcppExport SEXP _SCP_cosinor_pvals_cpp(SEXP exprSEXP, SEXP timesSEXP, SEXP periodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< double >::type period(periodSEXP);
    rcpp_result_gen = Rcpp::wrap(cosinor_pvals_cpp(expr, times, period));
    return rcpp_result_gen;
END_RCPP
}
// sim_cosinor_expr_cpp
NumericMatrix sim_cosinor_expr_cpp(const NumericVector& mesor, const NumericVector& amplitude, const NumericVector& phase, const NumericVector& sigma, const NumericVector& times, double period, double alpha2, double alpha3);
RcppExport SEXP _SCP_sim_cosinor_expr_cpp(SEXP mesorSEXP, SEXP amplitudeSEXP, SEXP phaseSEXP, SEXP sigmaSEXP, SEXP timesSEXP, SEXP periodSEXP, SEXP alpha2SEXP, SEXP alpha3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type mesor(mesorSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type amplitude(amplitudeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type phase(phaseSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< double >::type period(periodSEXP);
    Rcpp::traits::input_parameter< double >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha3(alpha3SEXP);
    rcpp_result_gen = Rcpp::wrap(sim_cosinor_expr_cpp(mesor, amplitude, phase, sigma, times, period, alpha2, alpha3));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SCP_cosinor_pvals_cpp", (DL_FUNC) &_SCP_cosinor_pvals_cpp, 3},
    {"_SCP_sim_cosinor_expr_cpp", (DL_FUNC) &_SCP_sim_cosinor_expr_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_SCP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
