# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cosinor_pvals_cpp <- function(expr, times, period = 24.0) {
    .Call('_SCP_cosinor_pvals_cpp', PACKAGE = 'SCP', expr, times, period)
}

sim_cosinor_expr_cpp <- function(mesor, amplitude, phase, sigma, times, period = 24.0, alpha2 = 0.0, alpha3 = 0.0) {
    .Call('_SCP_sim_cosinor_expr_cpp', PACKAGE = 'SCP', mesor, amplitude, phase, sigma, times, period, alpha2, alpha3)
}

